version: '3.9'

services:
  postgres_db:
    image: postgres:17
    container_name: monada_postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Monada
    ports:
      - "5433:5432"  # Проброс порта для подключения с хоста
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
