version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: monada
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d monada"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl:
    build: .
    env_file:
      - .env  # Подгружаем переменные для Python-скрипта
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db  # Переопределяем хост БД для Docker
      DB_PORT: 5432
